name: Github Actions CI
on:
  push:
    branches:
      - main
jobs: 
  say-hello: 
    runs-on: ubuntu-latest

  env:
    MY_ENV_VAR: "This is a variable!"

    steps: 
      - name : Hello
      - run: echo "Hello, Github Actions "

      - name: My_variable
      - run: echo "MY_VARIABLE is ${{ env.MY_VARIABLE }}"