name: Github Actions CI
on:
  push:
    branches:
      - main
jobs: 
  say-hello: 
    runs-on: ubuntu-latest
    
    env:
      MY_VARIABLE: "This is a variable!"

    steps: 
      - name: Hello
        run: echo "Hello, Github Actions"

      - name: My_variable
        run: echo "MY_VARIABLE is ${{ env.MY_VARIABLE }}"

      - name: My_secret
        run: echo "MY_SECRET is ${{ secrets.MY_SECRET }}"

      - name: Créer un fichier
        run: echo "Hello, world!" > hello.txt

      - name: Afficher le contenu de hello.txt
        run: cat hello.txt