name: Github Actions CI
on:
  push:
    branches:
      - main
jobs: 
  say-hello: 
    runs-on: ubuntu-latest
    
    env:
      MY_VARIABLE: "This is a variable!"

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Hello
        run: echo "Hello, Github Actions"

      - name: My_variable
        run: echo "MY_VARIABLE is ${{ env.MY_VARIABLE }}"

      - name: Créer un fichier
        run: echo "Hello, world!" > hello.txt

      - name: Afficher le contenu de hello.txt
        run: cat hello.txt